const jobs = [
  {
    title: 'Internal Auditor-Credit',
    posted: '2 weeks ago',
    postedDate: '2025-06-15',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'Finance',
    icon: '/icon.png',
    responsibilities: [
      'Perform audits on credit operations.',
      'Ensure compliance with internal credit policies.',
      'Report findings and provide recommendations for improvement.',
      'Assist in the development of internal control systems.',
    ],
    qualifications: [
      'Bachelor’s degree in Finance, Accounting or related field.',
      'Minimum 2 years of auditing experience.',
      'Strong analytical and communication skills.',
      'Familiar with Cambodian financial regulations.',
    ],
  },
  {
    title: 'Senior Internal Auditor-Credit',
    posted: '2 weeks ago',
    postedDate: '2025-06-14',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'Finance',
    icon: '/icon.png',
    responsibilities: [
      'Lead credit audit engagements.',
      'Review junior auditor work and provide guidance.',
      'Report audit results to senior management.',
      'Support compliance with regulatory standards.',
    ],
    qualifications: [
      'Bachelor’s or Master’s in Accounting, Finance.',
      '3+ years of internal audit experience.',
      'CPA or CIA certification is a plus.',
      'Excellent leadership and reporting skills.',
    ],
  },
  {
    title: 'Internal Auditor-Department',
    posted: '2 weeks ago',
    postedDate: '2025-06-12',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'Banking Operation',
    icon: '/icon.png',
    responsibilities: [
      'Audit department processes and documentation.',
      'Identify inefficiencies and recommend improvements.',
      'Ensure departmental compliance with internal policies.',
    ],
    qualifications: [
      'Degree in Banking, Finance, or related field.',
      'Experience in banking audit is preferred.',
      'Detail-oriented with good organizational skills.',
    ],
  },
  {
    title: 'Senior Digital Business Process Specialist',
    posted: '2 weeks ago',
    postedDate: '2025-06-13',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'IT',
    icon: '/icon.png',
    responsibilities: [
      'Analyze and improve digital business processes.',
      'Work with cross-functional teams to implement solutions.',
      'Lead automation initiatives.',
      'Provide training on digital tools and workflows.',
    ],
    qualifications: [
      'Bachelor’s in IT, Business or related field.',
      'Experience in digital transformation projects.',
      'Strong knowledge of business process modeling.',
      'Excellent problem-solving and communication skills.',
    ],
  },
  {
    title: 'Tax Operation Support Manager',
    posted: '2 weeks ago',
    postedDate: '2025-06-16',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'Finance',
    icon: '/icon.png',
    responsibilities: [
      'Ensure compliance with tax regulations.',
      'Prepare and review tax filings and documentation.',
      'Support internal and external tax audits.',
      'Advise management on tax strategies and planning.',
    ],
    qualifications: [
      'Degree in Accounting, Tax, or Finance.',
      'At least 3 years experience in tax operations.',
      'Knowledge of Cambodian tax laws.',
      'Strong analytical and documentation skills.',
    ],
  },
  {
    title: 'AML-CFT Compliance Supervisor',
    posted: '5 months ago',
    postedDate: '2025-02-01',
    location: 'Phnom Penh',
    type: 'Full Time',
    department: 'Compliance',
    icon: '/icon.png',
    responsibilities: [
      'Monitor regulation updates and conduct gap analysis.',
      'Assess compliance using checklists and reviews.',
      'Draft and review documents for regulatory bodies.',
      'Conduct compliance training for employees.',
      'Ensure accurate and timely reporting to NBC.',
      'Conduct risk-based compliance testing.',
      'Advise departments on implementing guidelines.',
    ],
    qualifications: [
      'Bachelor’s in Banking, Finance, Law, or related field.',
      '3+ years experience in compliance/AML-CFT.',
      'Knowledge of NBC laws and banking regulations.',
      'Strong analytical, investigation, and time management skills.',
      'High integrity and confidentiality.',
    ],
  },
]
export default jobs